version: "3.8"

services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000        # Set to your user ID
      - PGID=1000        # Set to your group ID
      - TZ=Etc/UTC       # Change to your timezone (e.g. Asia/Tehran)
      - SERVERURL=yourdomain.com  # or use your public IP
      - SERVERPORT=51820
      - PEERS=1          # Number of client configs to generate
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.13.13.0
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
    ports:
      - "51820:51820/udp"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
